include: _default_template_yaml
task: tomato_velocity_frequency
dataset_name: default
test_split: velocity_frequency
lmms_eval_specific_kwargs:
  default:
    post_prompt: "Only give the best option.\n"
  cambrians:
    post_prompt: "Answer with the option's letter from the given choices directly."
